name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    container: epitechcontent/epitest-docker:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: make
      - name: Run tests
        run: make tests_run
